# Generated by Django 4.1.4 on 2022-12-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=254, unique=True), max_length=30),
        ),
    ]
