# Generated by Django 4.1.4 on 2022-12-14 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('about_me', models.TextField()),
                ('skill1', models.CharField(blank=True, max_length=100, null=True)),
                ('skill2', models.CharField(blank=True, max_length=100, null=True)),
                ('skill3', models.CharField(blank=True, max_length=100, null=True)),
                ('fb', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
