# Generated by Django 4.1.4 on 2022-12-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_build', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='occupation',
            field=models.CharField(default='  ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='skill4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
